#
###################################
# Site wide configuration
####################################
#
title:       "Jorge Suja"
description: "Programador Ruby & Java"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Madrid
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jorge Suja
  avatar: https://avatars0.githubusercontent.com/jorgesuja
  job: "Programador web"
  bio: "pure awesome"
  email: jorgesuja@hotmail.com
  disqus-shortname: jorgesujablog
  twitter: #username
  facebook: #username
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jorgesuja
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jorge-suja-garrido-a71bb886
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
